//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.IMABS;

[assembly: RegisterDocumentType(BannerSection.CLASS_NAME, typeof(BannerSection))]

namespace CMS.DocumentEngine.Types.IMABS
{
	/// <summary>
	/// Represents a content item of type BannerSection.
	/// </summary>
	public partial class BannerSection : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "IMABS.BannerSection";


		/// <summary>
		/// The instance of the class that provides extended API for working with BannerSection fields.
		/// </summary>
		private readonly BannerSectionFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BannerSectionID.
		/// </summary>
		[DatabaseIDField]
		public int BannerSectionID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BannerSectionID"), 0);
			}
			set
			{
				SetValue("BannerSectionID", value);
			}
		}


		/// <summary>
		/// Content on banner.
		/// </summary>
		[DatabaseField]
		public string BannerHeading
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BannerHeading"), @"");
			}
			set
			{
				SetValue("BannerHeading", value);
			}
		}


		/// <summary>
		/// Navigation Text.
		/// </summary>
		[DatabaseField]
		public string BannerBreadcrumbsTitle
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BannerBreadcrumbsTitle"), @"");
			}
			set
			{
				SetValue("BannerBreadcrumbsTitle", value);
			}
		}


		/// <summary>
		/// Show on home page.
		/// </summary>
		[DatabaseField]
		public bool IsActiveBanner
		{
			get
			{
				return ValidationHelper.GetBoolean(GetValue("IsActiveBanner"), true);
			}
			set
			{
				SetValue("IsActiveBanner", value);
			}
		}


		/// <summary>
		/// Desktop Image.
		/// </summary>
		[DatabaseField]
		public string DesktopBanner
		{
			get
			{
				return ValidationHelper.GetString(GetValue("DesktopBanner"), @"");
			}
			set
			{
				SetValue("DesktopBanner", value);
			}
		}


		/// <summary>
		/// Tablet banner.
		/// </summary>
		[DatabaseField]
		public string TabletBanner
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TabletBanner"), @"");
			}
			set
			{
				SetValue("TabletBanner", value);
			}
		}


		/// <summary>
		/// Mobile banner.
		/// </summary>
		[DatabaseField]
		public string MobileBanner
		{
			get
			{
				return ValidationHelper.GetString(GetValue("MobileBanner"), @"");
			}
			set
			{
				SetValue("MobileBanner", value);
			}
		}


		/// <summary>
		/// Button Text.
		/// </summary>
		[DatabaseField]
		public string ButtonLinkName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonLinkName"), @"");
			}
			set
			{
				SetValue("ButtonLinkName", value);
			}
		}


		/// <summary>
		/// Button Link.
		/// </summary>
		[DatabaseField]
		public string ButtonRedirectionUrl
		{
			get
			{
				return ValidationHelper.GetString(GetValue("ButtonRedirectionUrl"), @"");
			}
			set
			{
				SetValue("ButtonRedirectionUrl", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BannerSection fields.
		/// </summary>
		[RegisterProperty]
		public BannerSectionFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BannerSection fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BannerSectionFields : AbstractHierarchicalObject<BannerSectionFields>
		{
			/// <summary>
			/// The content item of type BannerSection that is a target of the extended API.
			/// </summary>
			private readonly BannerSection mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BannerSectionFields" /> class with the specified content item of type BannerSection.
			/// </summary>
			/// <param name="instance">The content item of type BannerSection that is a target of the extended API.</param>
			public BannerSectionFields(BannerSection instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BannerSectionID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BannerSectionID;
				}
				set
				{
					mInstance.BannerSectionID = value;
				}
			}


			/// <summary>
			/// Content on banner.
			/// </summary>
			public string BannerHeading
			{
				get
				{
					return mInstance.BannerHeading;
				}
				set
				{
					mInstance.BannerHeading = value;
				}
			}


			/// <summary>
			/// Navigation Text.
			/// </summary>
			public string BannerBreadcrumbsTitle
			{
				get
				{
					return mInstance.BannerBreadcrumbsTitle;
				}
				set
				{
					mInstance.BannerBreadcrumbsTitle = value;
				}
			}


			/// <summary>
			/// Show on home page.
			/// </summary>
			public bool IsActiveBanner
			{
				get
				{
					return mInstance.IsActiveBanner;
				}
				set
				{
					mInstance.IsActiveBanner = value;
				}
			}


			/// <summary>
			/// Desktop Image.
			/// </summary>
			public string DesktopBanner
			{
				get
				{
					return mInstance.DesktopBanner;
				}
				set
				{
					mInstance.DesktopBanner = value;
				}
			}


			/// <summary>
			/// Tablet banner.
			/// </summary>
			public string TabletBanner
			{
				get
				{
					return mInstance.TabletBanner;
				}
				set
				{
					mInstance.TabletBanner = value;
				}
			}


			/// <summary>
			/// Mobile banner.
			/// </summary>
			public string MobileBanner
			{
				get
				{
					return mInstance.MobileBanner;
				}
				set
				{
					mInstance.MobileBanner = value;
				}
			}


			/// <summary>
			/// Button Text.
			/// </summary>
			public string ButtonLinkName
			{
				get
				{
					return mInstance.ButtonLinkName;
				}
				set
				{
					mInstance.ButtonLinkName = value;
				}
			}


			/// <summary>
			/// Button Link.
			/// </summary>
			public string ButtonRedirectionUrl
			{
				get
				{
					return mInstance.ButtonRedirectionUrl;
				}
				set
				{
					mInstance.ButtonRedirectionUrl = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BannerSection" /> class.
		/// </summary>
		public BannerSection() : base(CLASS_NAME)
		{
			mFields = new BannerSectionFields(this);
		}

		#endregion
	}
}